### ISSUE TITLE
Requirements.txt is out of date.

### ISSUE THREAD

**Issue by jsharf** [jmercouris/IPSRC#2]
It looks like ipgetter is no longer a valid python package. Instead, it's ipgetter2 (?).

I can work on a fix for this myself over the weekend, but for now I'm just making a quick workaround and filing this issue.

Thanks for the nifty tool.

ERROR: Could not find a version that satisfies the requirement ipgetter==0.7 (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for ipgetter==0.7 (from -r requirements.txt (line 4))

**Comment by jsharf** [comment]
Oh, I almost forgot to include the command I ran:

$ pip3 install -r requirements.txt

**Comment by jmercouris** [comment]
Thanks for the report :-)

Feel free to submit a PR!

**Comment by jsharf** [comment]
#3
